Sergio/templates list and form
peillis/siwapp pull request #102
Opened 2021-12-27 13:43 UTC by olirods

![index](https://user-images.githubusercontent.com/49884623/147477361-8bd98cc7-5da8-4725-acd0-14dd180c39e7.png)
![form](https://user-images.githubusercontent.com/49884623/147477365-4733ff21-d0c5-48f0-b30b-bce082d59728.png)

2021-12-27 15:15 UTC, peillis requested changes

2021-12-27 15:15 UTC, peillis commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
por que no recibes aqui el parametro ya bien en vez de tener que mofificarlo? Es decir: `:print_default` y `:email_default`

2021-12-27 15:23 UTC, olirods commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Aah ya. Yo era porque la API fuera más intuitiva y no se tuviese que repetir la palabra 'default' dos veces en las llamadas a la funcion e.g. `get_default(:print)` en vez de `get_default(:print_default)`

2021-12-28 07:59 UTC, peillis commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
tienes razón que esas llamadas quedan muy reiterativas, pero lo otro es como muy artificioso. No sé si podríamos encontrar otros nombres para las fn

2021-12-28 08:07 UTC, olirods commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Como son solo dos, quizás se podría hacer por pattern matching, que cuando sea :email meter directamente la key como :email_default y te ahorras tener que elaborarla con la string.

2021-12-28 08:11 UTC, peillis commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
ya, lo que pasa es q hacer un pattern matching para hacer lo mismo es igual de raro me parece

2021-12-28 08:37 UTC, olirods commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Ya. Pues no sé, es que el nombre más intuitivo para mí es `get_default`. Incluso ahora estoy pensando que `change_default `quizas estaría mejor llamándose `set_default`.

2021-12-28 08:42 UTC, peillis commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Se me ocurre podrías utilizar el mismo get sin más: `get(:print_default)`. Recibiendo atom como parámetro.

2021-12-28 08:48 UTC, olirods commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Vale. Pero y `change_default`? Que también usa lo mismo para sacar la key. `set(:print_default)` ?

2021-12-28 08:50 UTC, peillis commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
seguramente esa sea mejor como tu dices, set_default

2021-12-28 08:52 UTC, olirods commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Vale bueno voy a hacer esos cambios en otros PR que este realmente era del list y el form. Y aprovecho para cambiar también lo de que `change_default` ya no se le llamaba sin parámetros.

2021-12-28 09:16 UTC, olirods commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Ya he hecho el otro PR, cuando lo apruebes actualizo este con las llamadas nuevas

2021-12-28 09:46 UTC, olirods commented on lib/siwapp/templates.ex
>    @spec get_default(:print | :email) :: %Template{} | nil
Ya está actualizado

2021-12-28 10:36 UTC, peillis approved these changes

2021-12-28 10:36 UTC, merged