PDF download
peillis/siwapp pull request #209
Opened 2022-01-21 10:56 UTC by Pabloj20

2022-01-21 12:41 UTC, peillis requested changes
no escribas ficheros a disco

2022-01-25 10:15 UTC, nurietzsche2021 reviewed
El resto está muy bien. Solo cambiaría el pdf_file porque lleva a confusión

2022-01-25 10:15 UTC, nurietzsche2021 commented on lib/siwapp_web/controllers/page_controller.ex
> +    pdf_file = invoice.series.code <> "-" <> Integer.to_string(invoice.number) <> ".pdf"
Yo pondría pdf_name en vez de pdf_file porque lleva a confusión

2022-01-25 10:32 UTC, nurietzsche2021 approved these changes
Genial!!!!!!

2022-01-25 10:32 UTC, nurietzsche2021 commented on lib/siwapp_web/controllers/page_controller.ex
> +    IO.inspect(conn)
quita esto

2022-01-25 12:50 UTC, olirods approved these changes
Great :japan:

2022-01-26 08:43 UTC, peillis requested changes

2022-01-26 08:43 UTC, peillis commented on lib/siwapp_web/controllers/page_controller.ex
> +    pdf_name = invoice.series.code <> "-" <> Integer.to_string(invoice.number) <> ".pdf"
Mejor que esto es usar string interpolation

2022-01-26 08:43 UTC, peillis commented on lib/siwapp_web/controllers/page_controller.ex
> +    }
¿por qué lo has hecho con cookies en vez de con un json web token de la api?
Ten en cuenta que en cualquier caso bajarse el pdf tiene que estar accesible a través de la api.

2022-01-26 08:43 UTC, peillis commented on lib/siwapp_web/controllers/page_controller.ex
> +        end
Esta fn la puedes anonimizar y usar el &1

2022-01-26 09:34 UTC, Pabloj20 commented on lib/siwapp_web/controllers/page_controller.ex
> +    }
porque la dependencia ChromicPDF necesita configurar una cookie con esos campos concretos

2022-01-28 20:16 UTC, nurietzsche2021 approved these changes
Se entiende muy bien!

2022-01-31 10:56 UTC, closed without merging