customer autocomplete
peillis/siwapp pull request #224
Opened 2022-01-25 10:03 UTC by olirods

solve #211

Al empezar a escribir, te salen las posibles opciones de Customers, y al seleccionar te rellena los otros campos. Tanto en Invoices como en Recurring Invoices.

Faltaría ponerlo como una lista cuando son muchos customers posibles y dejarlo bonito (#220)

2022-01-25 10:22 UTC, nurietzsche2021 requested changes

2022-01-25 10:22 UTC, nurietzsche2021 commented on lib/siwapp_web/live/invoices_live/edit.ex
> +    customer_input = Map.get(params, "name")
customer_name_input se entendería mejor, la verdad

2022-01-25 10:22 UTC, nurietzsche2021 commented on lib/siwapp_web/live/invoices_live/edit.ex
> +  defp suggest_customers(customer_input) do
Yo haría una query ya específica que te devuelva los clientes filtrados

2022-01-25 13:16 UTC, olirods commented on lib/siwapp_web/live/invoices_live/edit.ex
> +    customer_input = Map.get(params, "name")
Done:)

2022-01-26 09:12 UTC, olirods commented on lib/siwapp_web/live/invoices_live/edit.ex
> +  defp suggest_customers(customer_input) do
Done:) ahora está mucho mejor thank u

2022-01-27 10:54 UTC, olirods commented on lib/siwapp_web/live/recurring_invoices_live/edit.ex
> +
Para RecurringInvoices lo he copiado directamente, y ya hay un issue (#218) para que todo esto común de Invoices y RecurringInvoices se lleve a otro sitio común

2022-01-27 10:58 UTC, RodrigoMolinaMadrid requested changes

2022-01-27 10:58 UTC, RodrigoMolinaMadrid commented on lib/siwapp_web/live/invoices_live/edit.ex
> +  def handle_event("pick_customer", %{"name" => customer_name, "id" => customer_id}, socket) do
No hace falta capturar el name, lo puedes conseguir del customer

2022-01-27 10:58 UTC, RodrigoMolinaMadrid commented on lib/siwapp_web/live/invoices_live/edit.ex
> +    Customers.get(customer_id)
Este Customers.get creo que no hace nada

2022-01-27 10:58 UTC, RodrigoMolinaMadrid commented on lib/siwapp_web/live/recurring_invoices_live/edit.ex
> +    Customers.get(customer_id)
Pasa lo mismo. Creo que sobra el Customers.get

2022-01-27 11:06 UTC, olirods commented on lib/siwapp_web/live/recurring_invoices_live/edit.ex
> +    Customers.get(customer_id)
Done:)

2022-01-27 11:06 UTC, olirods commented on lib/siwapp_web/live/invoices_live/edit.ex
> +    Customers.get(customer_id)
Done:)

2022-01-27 11:06 UTC, olirods commented on lib/siwapp_web/live/invoices_live/edit.ex
> +  def handle_event("pick_customer", %{"name" => customer_name, "id" => customer_id}, socket) do
Done:)

2022-01-27 11:14 UTC, nurietzsche2021 approved these changes
Yo lo veo fantástico ahora

2022-01-27 11:20 UTC, RodrigoMolinaMadrid approved these changes

2022-01-27 12:01 UTC, peillis requested changes
pon todo el comportamiento en el customer component

2022-01-28 14:08 UTC, peillis approved these changes

2022-01-28 14:08 UTC, merged