Taxes state in invoice form
peillis/siwapp pull request #228
Opened 2022-01-25 12:20 UTC by olirods

fix #212 (Como el componente para introducir los taxes era un componente especial, no se llamaba al phx-change (función validate) cuando se metían nuevas taxes, y por tanto no se introducían estas taxes en los 'changes' del changeset. Por esta razón, cuando añadías un item nuevo y se actualizaban los datos según el contenido del changeset, como los taxes no estaban en el changeset, desaparecían)

Se ha solucionado finalmente mandando un mensaje desde el componente de taxes al LiveView padre (InvoicesLive form) cada vez que se añade o se quita un tax. Cuando el LiveView lo recibe, lo que hace es actualizar el changeset incluyendo estos taxes nuevos en los items correspondientes.

Esta forma de actualizar el changeset con items nuevos (update_changeset_with_items/3), también se ha aplicado cuando añades o quitas un item, de forma que actualice el changeset también porque antes no lo hacía.

2022-01-25 12:21 UTC, olirods commented on lib/siwapp/invoices/item.ex
> -  # an error in the changeset.
Aquí sólo he añadido algunos casos que daban error con el tema de items ya existentes con taxes y tal, y ya he hecho un poco de refactoring dividiendo la función en dos

2022-01-28 12:30 UTC, Pabloj20 approved these changes

2022-01-28 12:30 UTC, Pabloj20 commented on lib/siwapp_web/live/invoices_live/edit.ex
> +    items = Ecto.Changeset.get_field(changeset, :items) ++ [Invoices.change_item(%Item{})]
no entiendo por qué concatenas un changeset que no tiene información

2022-01-28 20:21 UTC, nurietzsche2021 requested changes
Ahora tienes conflictos. Yo te diría de arreglarlos y hacer un nuevo pr de esto cuando el form común de items esté mergeado

2022-01-28 20:36 UTC, closed without merging