default issue_date and due_date for invoice + tests
peillis/siwapp pull request #231
Opened 2022-01-26 11:41 UTC by olirods

solves #167

2022-01-27 10:42 UTC, Pabloj20 approved these changes

2022-01-27 11:23 UTC, nurietzsche2021 approved these changes
Yo los veo bien

2022-01-27 12:21 UTC, peillis requested changes

2022-01-27 12:21 UTC, peillis commented on test/siwapp/invoices/invoice_test.exs
> +    ]
Esto deberia ser un fixture de settings

2022-01-28 11:51 UTC, olirods commented on test/siwapp/invoices/invoice_test.exs
> +    ]
Hecho:)

2022-01-28 14:11 UTC, peillis approved these changes

2022-01-28 14:11 UTC, peillis commented on lib/siwapp/invoices/invoice.ex
> +    due_date = Date.add(issue_date, String.to_integer(settings.days_to_due))
Esta forma de coger los setting es demasiado elaborada. Lo ideal sería una fn tipo `Settings.get(:days_to_due)` pero hacerlo en otro issue.

2022-01-28 14:11 UTC, merged