Pablo/search
peillis/siwapp pull request #242
Opened 2022-01-28 11:15 UTC by Pabloj20

Es un buscador incluido en el menú cuya única funcionalidad es la de aparecer y desaparecer. Las funcionalidades solicitar parámetros etc, se harán con posterioridad

2022-01-28 11:24 UTC, Pabloj20 commented
![Captura de pantalla de 2022-01-28 12-25-23](https://user-images.githubusercontent.com/66000403/151538863-7d9fceb8-d639-4100-86f3-aa65127317d1.png)

2022-01-28 17:07 UTC, olirods commented
Una cosa que me acabo de dar cuenta que en el otro PR no caí, que Tags ya no existen en nuestro Siwapp, ¿no?

2022-01-28 17:09 UTC, olirods commented
Y con respecto a la funcionalidad esta de desplegarlo y no, ¿no hay forma de hacerlo con LiveView y no Javascript? No sé si esto podría ser un Live Component o algo así y que se display o no según un evento phx-click y el valor de una variable del socket

2022-01-28 17:14 UTC, peillis commented on assets/js/app.js
> +)
Antes de escribir javascript hay que rellenar un formulario de 20 folios, mandarlo al Parlamento Europeo, que lo aprueben allí, que el Tribunal Constitucional esté de acuerdo y emita jurisprudencia sobre el tema. Cuando se cumpla todo eso... escribes javascript.

2022-01-28 20:19 UTC, nurietzsche2021 requested changes
Lo mismo que Sergio y Enrique... Pinta mal eso de usar JavaScript teniendo LiveViews

2022-02-01 10:13 UTC, Pabloj20 commented
![Captura de pantalla de 2022-02-01 11-13-51](https://user-images.githubusercontent.com/66000403/151950164-8da50f54-54ee-42cf-a10c-42f375d88a60.png)

2022-02-01 10:14 UTC, olirods approved these changes
:)

2022-02-01 10:41 UTC, nurietzsche2021 approved these changes

2022-02-01 11:35 UTC, peillis requested changes

2022-02-01 11:35 UTC, peillis commented on lib/siwapp_web/live/search_live/index.ex
> +    JS.toggle(to: "#search-menu")
puedes poner el JS.toggle directamente en el template

2022-02-01 11:51 UTC, peillis approved these changes

2022-02-01 11:51 UTC, merged