Rodri/currency
peillis/siwapp pull request #243
Opened 2022-01-28 15:28 UTC by RodrigoMolinaMadrid

Ya está la función set_currency en una view, pero hay que llamarla con la ruta completa del módulo cuando queremos renderizar el html del print_defaul.html

2022-01-28 17:36 UTC, peillis requested changes

2022-01-28 17:36 UTC, peillis commented on lib/siwapp_web/live/invoices_live/edit.ex
> +  end
¿donde estás usando estas fns?

2022-01-28 17:36 UTC, peillis commented on lib/siwapp_web/views/iframe_view.ex
> +  def set_currency(value, currency), do: PageView.set_currency(value, currency)
¿por qué no usas directamente la fn del PageView en vez de crear otra?

2022-01-31 08:48 UTC, RodrigoMolinaMadrid commented on lib/siwapp_web/live/invoices_live/edit.ex
> +  end
desde el template de invoices_edit.html

2022-01-31 09:00 UTC, peillis approved these changes

2022-01-31 09:00 UTC, merged