Nurietzsche/generate invoices
peillis/siwapp pull request #258
Opened 2022-02-01 11:59 UTC by nurietzsche2021

fixes #252

2022-02-02 08:40 UTC, RodrigoMolinaMadrid approved these changes

2022-02-02 08:46 UTC, Pabloj20 approved these changes

2022-02-02 14:34 UTC, peillis requested changes

2022-02-02 14:34 UTC, peillis commented on lib/siwapp/recurring_invoices.ex
> +    |> Map.filter(fn {key, _value} -> key in identical_fields() end)
haciendo Map.from_struct y luego struct del map es suficiente y te ahorras toda esta logica de identical_fields

2022-02-07 08:54 UTC, Pabloj20 approved these changes

2022-02-07 12:24 UTC, peillis requested changes

2022-02-07 12:24 UTC, peillis commented on lib/siwapp/recurring_invoices.ex
> +          do: Invoices.create(build_invoice_attrs(rec_inv))
Estás invocando 2 veces el invoices_to_generate y además todo este if+for se podría hacer en un simple Enum.each

2022-02-08 13:27 UTC, olirods approved these changes

2022-02-09 09:10 UTC, Pabloj20 approved these changes

2022-02-09 09:10 UTC, RodrigoMolinaMadrid approved these changes
Guay

2022-02-09 11:20 UTC, peillis requested changes

2022-02-09 11:20 UTC, peillis commented on lib/siwapp/recurring_invoices.ex
> +    Enum.each(1..n//1, fn _ -> Invoices.create(build_invoice_attrs(rec_inv)) end)
Para que añades el //1?

2022-02-09 18:14 UTC, nurietzsche2021 commented on lib/siwapp/recurring_invoices.ex
> +    Enum.each(1..n//1, fn _ -> Invoices.create(build_invoice_attrs(rec_inv)) end)
Si no añado el //1, si n<1, 1..n es [n, .., 1]. La generación de estas listas ignora la posición de los extremos del rango, si estaban invertidos, la generación del siguiente número se realiza restando en vez de sumando y ya. Es decir, sin poner un //k explícito, pasa de un número a otro para generar una lista según le convenga para que tal lista de un extremo a otro se genere (//1 o //-1)

2022-02-10 08:28 UTC, peillis approved these changes

2022-02-10 08:28 UTC, merged