Nurietzsche/recurring invoice items
peillis/siwapp pull request #260
Opened 2022-02-02 10:13 UTC by nurietzsche2021

fixes #214 

Los items de una recurring invoice se guardan como lista de mapas con los campos del schema de Invoices.Item y con su lista de taxes también.

Los errores que falta por arreglar son comunes a invoice y recurring invoice y se deben al comportamiento anómalo del selector de taxes.

Como esto todavía no está claro, de momento en la recurring invoice taxes amounts no hace nada

2022-02-02 10:52 UTC, olirods approved these changes
:smile_cat:

2022-02-02 11:30 UTC, RodrigoMolinaMadrid approved these changes
Guay, si sigue funcionando el formulario de invoices como antes (fallando de vez en cuando con el multiselect pero se pintan bien las cantidades todo) I give you my aprove

2022-02-02 12:44 UTC, olirods approved these changes

2022-02-02 13:59 UTC, RodrigoMolinaMadrid approved these changes
Lo veo guay

2022-02-02 15:55 UTC, peillis requested changes
Habla con Sergio porque lo he comentado con él, pero básicamente has hecho un módulo lleno de ifs distinguiendo si estás en Invoice o RecurringInvoice, cuando la idea es hacer una adaptación de la lista de mapas del recurring invoice a la estructura propia del Invoice.
Si se me escapa algo me decís.

2022-02-04 12:03 UTC, nurietzsche2021 commented on lib/siwapp/invoice_helper.ex
> +
Estas funciones son exactamente las mismas que había en el boundary de invoice, sólo las he movido

2022-02-04 12:05 UTC, nurietzsche2021 commented on lib/siwapp_web/live/invoices_live/edit.ex
> +      Ecto.Changeset.get_field(socket.assigns.changeset, :items) ++
Hacen lo mismo que antes, solo he cambiado la notación a una más reducida

2022-02-04 12:28 UTC, olirods approved these changes

2022-02-04 12:37 UTC, nurietzsche2021 commented on lib/siwapp_web/live/recurring_invoices_live/edit.ex
> +  defp build_rec_params(params) do
Estas funciones para montar los parámetros no estarán cuando las taxes funcionen correctamente, ya que se enviarán mejor los parámetros del selector y simplemente anidaremos los items

2022-02-07 09:02 UTC, RodrigoMolinaMadrid approved these changes

2022-02-07 14:47 UTC, peillis requested changes

2022-02-07 14:47 UTC, peillis commented on lib/siwapp/invoice_helper.ex
> +  # Performs the totals calculations for net_amount, taxes_amounts and gross_amount fields.
si la fn es pública ponle la doc pública.

2022-02-07 14:47 UTC, peillis commented on lib/siwapp/recurring_invoices/recurring_invoice.ex
> +  defp transform_items(changeset) do
Deberias explicar un poco en comentarios qué significa transform y untransform, apply, unapply, por qué se hacen...

2022-02-07 14:47 UTC, peillis commented on lib/siwapp/recurring_invoices.ex
> +    |> RecurringInvoice.changeset(attrs, :save)
No deberia haber un changeset de "save", sino aquí mismo aplicar lo que sea necesario antes de hacer save.

2022-02-07 14:47 UTC, peillis commented on lib/siwapp_web/live/recurring_invoices_live/edit.ex
> +    [Item.changeset(%Item{}, %{})]
¿para que es esto que no hace nada?

2022-02-07 14:47 UTC, peillis commented on lib/siwapp_web/templates/item/item_form.html.heex
> +    <%= for fi <- @inputs_for do %>
¿por que empieza indentado este fichero?

2022-02-07 14:47 UTC, peillis commented on lib/siwapp_web/views/item_view.ex
> +    |> :erlang.float_to_binary(decimals: 2)
¿por qué no Float.to_string?

2022-02-08 09:06 UTC, RodrigoMolinaMadrid commented on lib/siwapp_web/views/item_view.ex
> +    |> :erlang.float_to_binary(decimals: 2)
Esa función la hice yo y Nuria solo la ha cambiado de sitio. Era para que se respetara siempre el formato que se muestra en el formulario y en el iframe. Para que sea igual a la que ofrece la librería Money

2022-02-09 09:05 UTC, RodrigoMolinaMadrid approved these changes

2022-02-09 10:41 UTC, peillis approved these changes

2022-02-09 10:42 UTC, peillis commented
No se puede subir porque tiene conflictos

2022-02-10 08:42 UTC, closed without merging