Nurietzsche/indexes
peillis/siwapp pull request #286
Opened 2022-02-04 12:40 UTC by nurietzsche2021

fixes #261

2022-02-07 08:42 UTC, Pabloj20 requested changes

2022-02-07 08:42 UTC, Pabloj20 commented on lib/siwapp_web/live/invoices_live/index.html.heex
> +        <td><%= invoice.series.code <> "-" <> Integer.to_string(invoice.number) %></td>
string interpolation mejor

2022-02-07 08:54 UTC, Pabloj20 approved these changes

2022-02-07 08:55 UTC, RodrigoMolinaMadrid approved these changes

2022-02-07 13:47 UTC, peillis requested changes

2022-02-07 13:47 UTC, peillis commented on lib/siwapp/invoices.ex
> +    |> Repo.preload(:series)
si los preload son necesarios siempre en estas queries es mejor que se resuelvan en una sola query y no hacerlos como los haces aquí que ejecutan varias queries. https://hexdocs.pm/ecto/Ecto.Query.html#preload/3

2022-02-07 17:29 UTC, peillis commented
El string interpolation que proponía @Pabloj20 ¿por qué lo has dado por resuelto?

2022-02-08 08:38 UTC, Pabloj20 approved these changes

2022-02-08 08:39 UTC, RodrigoMolinaMadrid approved these changes

2022-02-08 10:29 UTC, merged