Pablo/search query
peillis/siwapp pull request #290
Opened 2022-02-08 09:29 UTC by Pabloj20

En este pr me he centrado en la búsqueda por nombre, email o id para cada tabla(customer, recurring_invoices e invoices). Al escribir algo en el buscador, se genera un evento llamado "search" que llama a su vez a una query para realizar dicha búsqueda, guardar las nuevas invoices, customers o recurring_invoices en el socket y renderizarlos.

2022-02-08 09:40 UTC, Pabloj20 commented
Además de lo anterior, he implementado 3 componentes que contienen el contenido (valga la redundancia) de cada una de las vistas (invoices, customers y recurring_invoices)

2022-02-08 09:49 UTC, RodrigoMolinaMadrid approved these changes
Lo apruebo, pero hay una cosa que va a haber que cambiar en un futuro. Cuando llegues al final de la página haciendo scroll con las invoices o customers ya filtradas, el evento "load-more" va a cargar 20 invoices más pero esta vez sin hacer el filtro de los parámetros de la búsqueda

2022-02-08 12:57 UTC, nurietzsche2021 approved these changes
A mí me gusta!

2022-02-08 18:43 UTC, peillis requested changes

2022-02-08 18:43 UTC, peillis commented on lib/siwapp/customers.ex
> +    |> Query.paginate(0, 20)
no pongas paginacion a fuego, mira como está hecho el list

2022-02-08 18:43 UTC, peillis commented on lib/siwapp/customers.ex
> +  def filtered_customers(value) do
Bastaría con llamar a la fn "filtered" ya que al invocarla siempre va a ser como Customers.filtered y con tu nombre sería Customers.filtered_customers que es repetitivo.

2022-02-08 18:43 UTC, peillis commented on lib/siwapp/recurring_invoices.ex
> +    |> Repo.all()
Si siempre repites la misma query tiene pinta que lo puedes hacer de otra forma de forma que no repitas la misma fn en cada contexto.

2022-02-09 09:15 UTC, Pabloj20 commented on lib/siwapp/customers.ex
> +    |> Query.paginate(0, 20)
lo quito

2022-02-09 09:15 UTC, Pabloj20 commented on lib/siwapp/customers.ex
> +  def filtered_customers(value) do
lo cambio

2022-02-09 09:40 UTC, nurietzsche2021 commented on lib/siwapp/recurring_invoices.ex
> +    |> Repo.all()
Respecto a este comentario, estoy de acuerdo que podrías hacer un helper con filtered(queryable, value) y así la llamas en cada módulo con __MODULE__ por ejemplo

2022-02-09 09:42 UTC, nurietzsche2021 requested changes
Únelas en un helper si son todas iguales

2022-02-09 11:00 UTC, closed without merging