better seeds
peillis/siwapp pull request #293
Opened 2022-02-08 13:01 UTC by olirods

fixes #288 

![Captura de pantalla 2022-02-08 a las 13 56 55](https://user-images.githubusercontent.com/49884623/152991920-a70f2889-1f5d-4c91-bda3-88f432b3d7ab.png)
![Captura de pantalla 2022-02-08 a las 13 57 11](https://user-images.githubusercontent.com/49884623/152991932-96475dbb-aed3-4e43-b337-e5890ef83899.png)
![Captura de pantalla 2022-02-08 a las 13 57 17](https://user-images.githubusercontent.com/49884623/152991947-a8e457e7-6f48-4cb0-9ecd-f8923b5ee7cb.png)

2022-02-08 13:09 UTC, nurietzsche2021 approved these changes
Muy completas

2022-02-09 09:07 UTC, Pabloj20 approved these changes

2022-02-09 09:24 UTC, peillis requested changes

2022-02-09 09:24 UTC, peillis commented on mix.exs
> +      {:faker, "~> 0.17.0", only: [:test, :dev]}
pon las dependencias siempre ordenadas alfabéticamente

2022-02-09 09:24 UTC, peillis commented on priv/repo/seeds.exs
> +    paid: Enum.random(booleans),
Esto más que random lo tiene que "decidir" los payments, pero como todavía no existen se puede dar por bueno de momento.

2022-02-09 09:39 UTC, olirods commented on priv/repo/seeds.exs
> +    paid: Enum.random(booleans),
Ya si, lo había dejado así por ahora igual que recurring invoices hasta que estuviera del todo fijado como funciona.

2022-02-09 10:03 UTC, peillis approved these changes

2022-02-09 10:03 UTC, merged