Nurietzsche/customer index
peillis/siwapp pull request #302
Opened 2022-02-10 11:32 UTC by nurietzsche2021

fixes #264 

DINERO
Como véis, está pensado para que si hay más de una divisa o ninguna por cliente, se renderice directamente la cantidad de dinero. Las cantidades se calculan con querys a db. Cambié a esta opción, en vez de hacer preload y luego sumar con las invoices cargadas porque creo que eso debe ser más costoso, no sé.

SHOW
La vista de show es live para que se implemente más adelante el botón que añade la gráfica más tarde. Esta LV usa el index de invoices.

2022-02-11 09:03 UTC, Pabloj20 requested changes

2022-02-11 09:03 UTC, Pabloj20 commented on lib/siwapp_web/live/customer_live/index.ex
> +    case Customers.money(customer_id, type) do
el hecho de que estas dos funciones se llamen igual y que reciban los mismo argumentos a mi me resulta un poco confuso

2022-02-11 10:46 UTC, olirods commented on lib/siwapp/customers.ex
> +        [nil] -> nil
Con #309 se supone que ya no podrá ser nil la currency de una invoice, tiene valor por defecto, pero bueno mientras no se apruebe supongo que es mejor dejarlo así y ya en un futuro se quita esta condición

2022-02-11 10:46 UTC, olirods commented on lib/siwapp/customers.ex
> +    end
Si por lo que veo en la función amount al final tienes puesto un valor por defecto a 0 al lado de Repo.one(), no pueden ser nunca nil, ¿no?

2022-02-11 10:46 UTC, olirods commented on lib/siwapp_web/live/customer_live/index.ex
> +    case Customers.money(customer_id, type) do
Sí, y a mi el concepto money me parece en ambos casos un poco ambiguo.

2022-02-11 10:46 UTC, olirods commented on lib/siwapp_web/live/customer_live/index.ex
> +      {amount, currency} -> PageView.set_currency(amount, currency)
Esto ahora mismo ya no haría falta. A PageView.set_currency si lo llamas con currency==nil te mete él un valor, y ya después con #309 pues ni sucederá ese caso.

2022-02-14 07:50 UTC, closed without merging

2022-02-14 07:53 UTC, nurietzsche2021 commented on lib/siwapp/customers.ex
> +  def amount(customer_id, :due) do
Totalmente, la cambio

2022-02-14 07:54 UTC, nurietzsche2021 commented on lib/siwapp/customers.ex
> +        [nil] -> nil
Como ya se ha mergeado lo estoy quitando

2022-02-14 07:55 UTC, nurietzsche2021 commented on lib/siwapp/customers.ex
> +    end
Efectivamente, duplicado

2022-02-14 07:55 UTC, nurietzsche2021 commented on lib/siwapp_web/live/customer_live/index.ex
> +      {amount, currency} -> PageView.set_currency(amount, currency)
Te lo expliqué :)