Rodri/graphql invoices
peillis/siwapp pull request #310
Opened 2022-02-11 09:20 UTC by RodrigoMolinaMadrid

Simplemente he hecho los cambios que me ha dicho Enrique. He quitado los campos que no tiene sentido que tengan argumentos y he hecho que el Invoices.list funcione de manera similar a como lo hace en el customer (con el limit y el offset)

2022-02-11 12:20 UTC, Pabloj20 approved these changes

2022-02-11 12:42 UTC, peillis requested changes
cambia el schema de list invoices

2022-02-14 09:00 UTC, RodrigoMolinaMadrid commented
he unificado el listado de invoices con el de querys de un customer

2022-02-14 11:13 UTC, peillis requested changes

2022-02-14 11:13 UTC, peillis commented on lib/siwapp_web/resolvers/invoice.ex
> +  defp list_correct_units(invoices) do
Esta fn no hace nada muy especial. La puedes usar arriba sencillamente poniendo esto:
```elixir
|> Enum.map(&set_correct_units/1)
```

2022-02-14 11:13 UTC, peillis commented on lib/siwapp_web/resolvers/invoice.ex
> +    {:ok, invoice}
Pon `invoices` mejor, porque si no confunde y piensas que es solo una.

2022-02-14 11:13 UTC, peillis commented on lib/siwapp_web/views/page_view.ex
> +  def set_currency(value, nil, symbol: symbol), do: set_currency(value, :USD, symbol: symbol)
Este :USD no deberia estar aqui, o coger por lo menos de config.
De todas formas, deberian de poderse poner cifras sin currency asociada, que es lo que va a pasar cuando se sumen facturas de distintas currencies.

2022-02-14 11:58 UTC, RodrigoMolinaMadrid commented on lib/siwapp_web/views/page_view.ex
> +  def set_currency(value, nil, symbol: symbol), do: set_currency(value, :USD, symbol: symbol)
Con lo nuevo que ha hecho Sergio de las currencys ahora va a ser imposible que se cree una invoice y que su currency sea nil, ya que se le asigna la del settings por defecto. Por eso si esta línea desaparece no pasa nada.

2022-02-14 14:39 UTC, peillis requested changes

2022-02-14 14:39 UTC, peillis commented on lib/siwapp/invoices.ex
> +    options = Keyword.merge(default, options, fn _k, _v1, v2 -> v2 end)
¿por que no Keyword.merge(default, options) ?

2022-02-14 18:34 UTC, peillis commented on lib/siwapp_web/views/page_view.ex
> +  def set_currency(value, nil, symbol: symbol), do: set_currency(value, :USD, symbol: symbol)
Si eso es asi, esa validacion deberia estar en el changeset y en la bd. Es decir, que el currency nunca pueda ser nil.

2022-02-15 09:34 UTC, peillis approved these changes

2022-02-15 09:34 UTC, merged