Email regex validation
peillis/siwapp pull request #311
Opened 2022-02-11 10:56 UTC by RodrigoMolinaMadrid

Es super pequeño este PR
He añadido en el config.ex el regex por defecto de la validación del email.
Luego lo usamos en user, customer, invoice, recurrings invoices y en settings

2022-02-11 12:04 UTC, olirods approved these changes

2022-02-14 08:43 UTC, Pabloj20 approved these changes

2022-02-14 11:01 UTC, peillis requested changes
usa compile_env

2022-02-14 14:41 UTC, peillis requested changes

2022-02-14 14:41 UTC, peillis commented on lib/siwapp/recurring_invoices/recurring_invoice.ex
> +    |> validate_format(:email, Application.fetch_env!(:siwapp, :email_regex))
¿y aqui por que no?
Por favor, los primeros revisores de un PR sois vosotros mismos. Haz lo mismo que si tuvieras que revisar el de otro.

2022-02-15 09:36 UTC, peillis approved these changes

2022-02-15 09:36 UTC, merged