credo new config + solving errors
peillis/siwapp pull request #321
Opened 2022-02-14 10:51 UTC by olirods

2022-02-18 14:13 UTC, peillis requested changes

2022-02-18 14:13 UTC, peillis commented on head
> +Checking 111 source files (this might take a while) ...
Con este fichero no me extraña que añadas casi 2000 lineas :)

2022-02-21 10:26 UTC, RodrigoMolinaMadrid commented on head
> +Checking 111 source files (this might take a while) ...
jeje, fallo técnico. Ahora son solo 900

2022-02-21 11:13 UTC, peillis approved these changes

2022-02-21 11:13 UTC, merged