Rodri/unificar invoices list
peillis/siwapp pull request #334
Opened 2022-02-16 10:51 UTC by RodrigoMolinaMadrid

Ya que había muchas Invoices.list he unificado varias en una sola. De esta manera el scroll_listing sobra y se puede llamar a Invoices.list(limit: 20, offset: 30) por ejemplo. Y coge las 20 primeras invoices a partir de la 31. Lo mismo para recurring invoices.

Así manejamos los parámetros de entrada limit y offset más propios de sql y no usamos el paginate con el page y per_page

2022-02-17 08:50 UTC, Pabloj20 approved these changes

2022-02-17 09:31 UTC, nurietzsche2021 commented on lib/siwapp/invoices/invoice_query.ex
> +    |> where([i], i.due_date <= ^date_today)
Si vence hoy es past_due?

2022-02-17 09:32 UTC, nurietzsche2021 commented on lib/siwapp/recurring_invoices.ex
> +  def list(options \\ []) do
Si cambias una función, docs please, que aquí hay que entender mucho

2022-02-17 09:33 UTC, nurietzsche2021 commented on lib/siwapp/invoices/invoice_query.ex
>    def with_terms(query, terms) do
Rodri, ve poniendo documentación y specs, que nos va a hacer falta

2022-02-17 09:42 UTC, nurietzsche2021 requested changes
Para el nuevo mix credo nos piden spec y docs, tú debes saberlo. A llenar huequitos!

2022-02-17 10:06 UTC, RodrigoMolinaMadrid commented on lib/siwapp/invoices/invoice_query.ex
> +    |> where([i], i.due_date <= ^date_today)
Así está en la función status que pone el color rojo verde o amarillo. Yo en su día hice esta a partir de la otra pero no me di cuenta de que no concordaban. Ahora sí. Lo que no sé es si es así como ha de funcionar

2022-02-21 08:20 UTC, nurietzsche2021 approved these changes
Genial, gracias por ir unificando

2022-02-21 09:07 UTC, peillis requested changes

2022-02-21 09:07 UTC, peillis commented on lib/siwapp/invoices/invoice_query.ex
> +    |> where([i], i.due_date <= ^date_today)
No es past_due hasta que ha pasado el día, hasta el propio día de vencimiento es pending.

2022-02-21 10:28 UTC, RodrigoMolinaMadrid commented on lib/siwapp/invoices/invoice_query.ex
> +    |> where([i], i.due_date <= ^date_today)
Ok, entonces cambio tambień la función de status del contest de invoices

2022-02-21 11:17 UTC, peillis approved these changes

2022-02-21 12:34 UTC, peillis approved these changes

2022-02-21 12:34 UTC, merged