Rodri/past due mayor o igual
peillis/siwapp pull request #346
Opened 2022-02-21 12:33 UTC by RodrigoMolinaMadrid

Si el past_due seleccionado en el formulario es anterior a la issue_date el changeset es inválido

2022-02-21 14:47 UTC, olirods approved these changes
:ice_cream:

2022-02-22 09:19 UTC, nurietzsche2021 commented on lib/siwapp/invoices/invoice.ex
> +        due_date = Date.add(issue_date, String.to_integer(days_to_due))
Si aquí se había asignado una issue date "menor" que la due_date que tú estás asignando, no va a poner ningún error en este changeset.

2022-02-22 09:21 UTC, nurietzsche2021 commented on test/siwapp/invoices/invoice_test.exs
> +    test "If you provide a due date, that one is set if is equal or greater than the issue_date" do
De hecho, la gracia aquí sería hacer un test de dar issue date y no due date y ver que se añade automáticamente la due_date pero con un error, si queremos que funcione así, o que no te añada due date y añadir un error que te pide que introduzcas due date mayor o igual que issue date. No sé, me parece a mí

2022-02-22 09:22 UTC, nurietzsche2021 requested changes
Me parece que faltan casos. Mira los comentarios

2022-02-22 09:23 UTC, RodrigoMolinaMadrid commented on test/siwapp/invoices/invoice_test.exs
> +    test "If you provide a due date, that one is set if is equal or greater than the issue_date" do
ok, añado un test que corrobore el comportamiento que queremos

2022-02-23 08:46 UTC, nurietzsche2021 commented on lib/siwapp/settings/setting_bundle.ex
> +    |> non_neg_days_to_due()
Esta función lo que hace es validar days_to_due, llámala validate mejor, como el resto

2022-02-23 08:51 UTC, nurietzsche2021 commented on test/siwapp/invoices/invoice_test.exs
> +    test "If you provide a due date earlier than the issue date the changeset is invalid" do
No me refería sólo a este test. Mira tu función del changeset. Si no hay due_date asignada, se queda siempre con la generada automáticamente a partir de los days_to_due de Settings. Como te decía, esta fecha puede ser inválida. Hace falta un test en el que se introduzca una issue_date menor a la que se genera con Settings.value(:days_to_due). Como lo has programado, no dará ningún error, pero no tiene sentido!

2022-02-23 08:52 UTC, nurietzsche2021 requested changes
No has solucionado el problema que te dije

2022-02-23 09:20 UTC, nurietzsche2021 approved these changes
Perdona, malentendido mío

2022-02-23 16:49 UTC, merged