Nurietzsche/send email
peillis/siwapp pull request #347
Opened 2022-02-21 13:18 UTC by nurietzsche2021

En este pr lo que he hecho es implementar la funcionalidad de enviar una invoice por correo. No he linkeado el issue porque me falta:
- Usar el campo sent_by_email cuando la invoice esté enviada 
-  Dejar lista la configuración de Swoosh para que se pueda usar como en siwap/ror definiendo unas variables de entorno del SMTP

2022-02-21 16:55 UTC, RodrigoMolinaMadrid approved these changes

2022-02-22 07:56 UTC, Pabloj20 approved these changes

2022-02-22 11:47 UTC, peillis requested changes

2022-02-22 11:47 UTC, peillis commented on lib/siwapp/templates.ex
> +        k in [:company, :company_vat_id, :company_address, :company_email]
¿por qué filtras y no mandas todo? El template se encargará de coger lo que necesite.

2022-02-23 08:53 UTC, RodrigoMolinaMadrid approved these changes

2022-02-23 08:55 UTC, closed without merging