cambiando el assign number
peillis/siwapp pull request #353
Opened 2022-02-22 11:44 UTC by RodrigoMolinaMadrid

Hasta ahora se estaban haciendo querys en la función assign number. Se llamaba a esta función desde el la función Invoices.change(). Ahora solo le llama a esta función justo antes de un create o de un update.

2022-02-22 13:18 UTC, olirods requested changes
cuando se cambie de serie en el edit, que desaparezca el number del template

2022-02-23 10:06 UTC, RodrigoMolinaMadrid commented
Con este cambio se replica exactamente el comportamiento del Siwapp-demo. 

Cuando creas una invoice nueva en el formulario no aparece la casilla para rellenar el number y se le asigna automáticamente uno cuando se hace el save. 

Cuando editas una invoice ya creada te permite cambiar el number cuando estás en la serie original de esa invoice (get_change(@changeset, :series_id) == nil ). Si cambias de serie la casilla del number desaparece. En ambos casos el number que se le vaya a asignar se valida al hacer el save

2022-02-23 10:12 UTC, olirods approved these changes
:aerial_tramway:

2022-02-24 08:19 UTC, Pabloj20 approved these changes

2022-02-24 10:10 UTC, peillis approved these changes

2022-02-24 10:10 UTC, merged