payments
peillis/siwapp pull request #357
Opened 2022-02-22 12:35 UTC by olirods

fixes #272 

- migrations
- schema
- inclusión en el context de Invoices
- funcionando con inputs_for en invoice form. Sólo en edit.

! Se ha creado un módulo Siwapp.Invoices.AmountHelper para agrupar las funciones comunes de Item y Payments relativas al formato de item.unitary_cost / payment.amount

Issues relativos pendientes: #355, #356

2022-02-22 13:39 UTC, RodrigoMolinaMadrid approved these changes

2022-02-23 08:10 UTC, Pabloj20 requested changes

2022-02-23 08:10 UTC, Pabloj20 commented on lib/siwapp/invoices/payment.ex
> +    field :deleted_at, :utc_datetime
si hay un deleted_at en payment, cuando se borra un payment en invoices.ex, no debería añadirse la fecha de hoy al deleted_at en lugar de borrarlo como tal?

2022-02-23 08:48 UTC, olirods commented on lib/siwapp/invoices/payment.ex
> +    field :deleted_at, :utc_datetime
Sii tienes razón. Pero como las funciones para eso las tiene @RodrigoMolinaMadrid en el pr #351 pues cuando se mergee eso lo meto en payments en otro pr vale?

2022-02-24 08:21 UTC, Pabloj20 commented on lib/siwapp/invoices/payment.ex
> +    field :deleted_at, :utc_datetime
ya está mergeado me parece

2022-02-24 08:22 UTC, Pabloj20 commented on lib/siwapp/invoices/payment.ex
> +    field :deleted_at, :utc_datetime
vale vale te lo apruebo entonces

2022-02-24 08:22 UTC, Pabloj20 commented on lib/siwapp/invoices/payment.ex
> +    field :deleted_at, :utc_datetime
bueno tiene conflictos solucionalos que si no no me deja aprobarlos

2022-02-24 09:25 UTC, Pabloj20 approved these changes

2022-02-24 11:21 UTC, peillis requested changes

2022-02-24 11:21 UTC, peillis commented on lib/siwapp/invoices/payment.ex
> +    field :deleted_at, :utc_datetime
Quita el deleted_at

2022-02-24 11:45 UTC, peillis approved these changes

2022-02-24 11:45 UTC, merged