Nurietzsche/gen server
peillis/siwapp pull request #375
Opened 2022-02-24 12:08 UTC by nurietzsche2021

fixes #333 

Como véis he hecho un GenServer que se inicia cuando se monta la aplicación. Maneja la información de un mensaje que se envía a sí mismo cada 24h de generar facturas.

2022-02-24 12:21 UTC, Pabloj20 commented on lib/siwapp/invoices_generator.ex
> +    GenServer.start_link(__MODULE__, %{})
si el estado nunca cambia no es mejor poner nil?

2022-02-24 13:15 UTC, olirods commented on lib/siwapp/invoices_generator.ex
> +    |> RecurringInvoices.list()
Y como solo necesitas el id. No sería mejor hacer una función en el context que sea list_ids que te liste todos los ids que es lo único que necesitas, y asi te ahorras el rollo de maybe limit y maybe select

2022-02-24 13:19 UTC, olirods commented
Y otra cosa falta también meter la funcionalidad esta en el boton build recurring invoices del index no??

2022-02-25 09:38 UTC, nurietzsche2021 commented on lib/siwapp/invoices_generator.ex
> +    GenServer.start_link(__MODULE__, %{})
okay, hecho

2022-02-25 11:15 UTC, nurietzsche2021 commented on lib/siwapp/invoices_generator.ex
> +    Process.send_after(self(), :generate_invoices, 24 * 60 * 60 * 1000)
hechoo

2022-02-25 11:15 UTC, nurietzsche2021 commented on lib/siwapp/invoices_generator.ex
> +    |> RecurringInvoices.list()
Creo que tener una función así de completa es útil y así hacer listados tan personalizados como queramos sin tener que estar creando funciones nuevas constantemente para luego mergearlas

2022-02-25 11:56 UTC, Pabloj20 approved these changes

2022-02-25 14:41 UTC, olirods commented on lib/siwapp/invoices_generator.ex
> +    |> RecurringInvoices.list()
Yo no estoy de acuerdo:/ no me gusta:( jajaja pero yo apruebo si estais de acuerdo los demás @RodrigoMolinaMadrid @Pabloj20

2022-02-25 14:42 UTC, olirods approved these changes

2022-02-28 09:43 UTC, peillis requested changes

2022-02-28 09:43 UTC, peillis commented on lib/siwapp/application.ex
> +    Siwapp.InvoicesGenerator.start_link()
El genserver tiene que estar supervisado por el supervisor de la app.

2022-02-28 09:43 UTC, peillis commented on lib/siwapp_web/live/recurring_invoices_live/index.html.heex
> +        <button class="button is-purple" phx-click="generate_invoices">
¿por qué purple?

2022-02-28 13:01 UTC, Pabloj20 approved these changes

2022-02-28 13:05 UTC, RodrigoMolinaMadrid approved these changes

2022-03-01 08:24 UTC, peillis approved these changes

2022-03-01 08:24 UTC, merged