Rodri/calculate payments
peillis/siwapp pull request #387
Opened 2022-02-25 14:41 UTC by RodrigoMolinaMadrid

Se han añadido las funciones de los cálculos de los payments. 
También se ha cambiado la forma en la que se trabaja con los payments haciendo que funcionen como los items. Así, cuando se añade un payment se crean de cero sus params por defecto y luego estos se insertan el los params globales y luego  se pasa todo esto por el changeset para que esté disponible para el formulario.

También ha habido que hacer una función que reindexe los payments. De tal forma que si se tiene el 0, 1 y 2, y eliminamos el 1.
el 0 sigue siendo el 0 y el 2 pasa a ser el 1

2022-02-25 14:44 UTC, olirods approved these changes
:ice_cream: greattt

2022-02-28 07:53 UTC, nurietzsche2021 commented on lib/siwapp_web/live/invoices_live/edit.ex
> +    |> Enum.into(%{})
Para qué lo haces mapa, para volver a lista, para volver a mapa?

2022-02-28 08:00 UTC, nurietzsche2021 approved these changes
Quitando el comentario, bien, muy bien

2022-02-28 10:14 UTC, peillis requested changes

2022-02-28 10:14 UTC, peillis commented on lib/siwapp/invoices/invoice.ex
> +      |> round()
No hay que hacer round aquí para nada, estamos manejando enteros.

2022-02-28 10:14 UTC, peillis commented on lib/siwapp_web/live/invoices_live/edit.ex
> +      SiwappWeb.PageView.money_format(gross_amount - paid_amount, currency,
Las funciones de formato usarlas en los templates

2022-03-01 13:35 UTC, RodrigoMolinaMadrid commented
Ahora mismo hay una cosa que no funciona bien.

Para que tanto un item como un payment no se eliminen al actualizarlos se ha introducido un hidden_input del id que contiene el id de cada item/payment y lo envía a los params. Cuando el item/payment es nuevo este id es una cadena vacía.
El problema está en que si se crean dos items/params nuevos ambos tendrán una cadena vacía y eso hace que el changeset del segundo item/payment sea inválido. Incluso si en en changeset de items/payments eliminas de lo attrs el id cuando sea una cadena vacía en changeset sigue siendo inválido. El problema creo que está  en el cast_assoc del changeset de invoices.

2022-03-02 08:36 UTC, peillis requested changes

2022-03-02 12:40 UTC, peillis requested changes
quita los Phoenix.LiveView

2022-03-02 12:55 UTC, merged