Download CSV file
peillis/siwapp pull request #395
Opened 2022-03-01 11:05 UTC by Pabloj20

Este pr se basa en descargar un archivo CSV. Para ello primero envío los parámetros de búsqueda al controller que se encarga de descargar dicho archivo. Después busco mediante una query las invoices, customers o recurring_invoices que se encuentren para esos filtros, me quedo solo con los valores de cada campo,  lo paso por el CSV.encode y lo descargo

2022-03-01 12:11 UTC, nurietzsche2021 approved these changes

2022-03-01 15:26 UTC, olirods commented
He estao mirandolo y lo único que cuando descargas el csv sale en orden alfabetico, y en siwapp demo sale en un orden mas logico tipo id, customer_id, name, email y tal. Eso se podría arreglar facil?

2022-03-01 15:41 UTC, olirods commented on lib/siwapp_web/controllers/page_controller.ex
> +    |> Enum.sort()
Esto quizas es lo que las está poniendo en orden alfabetico??

2022-03-01 15:41 UTC, olirods commented on lib/siwapp_web/controllers/page_controller.ex
> +    |> Keyword.keys()
```suggestion
    queryable
    |> struct()
    |> Mappable.keys()
    |> Kernel.--(@reject_fields)
```

2022-03-01 15:41 UTC, olirods commented on lib/siwapp_web/controllers/page_controller.ex
> +    |> Keyword.keys()
Y he quitao lo de enum.sort porque quizas eso es lo que hace que esten en orden alfabetico??

2022-03-01 15:42 UTC, olirods commented on lib/siwapp_web/controllers/page_controller.ex
> +    |> Keyword.keys()
Mappable es una librería que yo he metido hace poco que a lo mejor no sabias de su existencia

2022-03-02 08:50 UTC, Pabloj20 commented on lib/siwapp_web/controllers/page_controller.ex
> +    |> Keyword.keys()
vale voy a ver cómo funciona

2022-03-02 12:06 UTC, Pabloj20 commented
En esta actualización, el archivo csv tiene ordenadas las claves según la variable @fields que hay en cada schema de invoices, recurring_invoice y customer

2022-03-02 12:08 UTC, olirods approved these changes
:kangaroo:

2022-03-02 14:22 UTC, nurietzsche2021 reviewed
Mejor!

2022-03-02 15:30 UTC, peillis requested changes

2022-03-02 15:30 UTC, peillis commented on lib/siwapp_web/controllers/page_controller.ex
> +    send_download(conn, {:binary, csv_content}, filename: "#{params["view"]}s.csv")
El download debe ser por stream, no generar todo el fichero y enviarlo, sino según se va generando hay que ir enviándolo. Esto es porque el espacio que puede ocupar puede llegar a ser mucho y reventar el sistema por memoria.

2022-03-03 11:35 UTC, closed without merging