Rodri/set paid button
peillis/siwapp pull request #412
Opened 2022-03-01 18:07 UTC by RodrigoMolinaMadrid

Es muy sencillo, por cada invoice que selecionemos con el checked se le crea un payment final con todo lo que le queda por pargar y se mandan los parámetros de todos los payments (los que ya había y el payment final) al Invoices.update

2022-03-02 14:20 UTC, nurietzsche2021 commented on lib/siwapp/invoices.ex
> +    payments_attrs = Enum.map(final_payments, &Map.take(&1, [:amount, :date, :notes, :id]))
De nuevo, en vez de hacer Map.take, por qué no Map.from_struct?

2022-03-02 14:21 UTC, nurietzsche2021 approved these changes
Considera lo de Map.from_struct

2022-03-02 15:05 UTC, olirods commented on lib/siwapp/invoices.ex
> +    payments_attrs = Enum.map(final_payments, &Map.take(&1, [:amount, :date, :notes, :id]))
Porque no le interesa coger todo, es que al final cuando vienen más atributos de los necesarios suele dar problemas

2022-03-02 15:05 UTC, olirods approved these changes

2022-03-02 15:33 UTC, peillis requested changes

2022-03-02 15:33 UTC, peillis commented on lib/siwapp/invoices.ex
> +      notes: "Set paid payment",
No pongas notas por defecto, mejor dejarlo vacío

2022-03-03 10:18 UTC, peillis requested changes
Tienes conflictos

2022-03-03 13:34 UTC, RodrigoMolinaMadrid commented on lib/siwapp/invoice_helper.ex
>    defp set_net_amount(changeset) do
He tenido que cambiar estas funciones porque cuando se hace un update de una invoice y no hay cambios en los items los items que ya había no pasan por el changeset. De tal manera que al hacer los cálculos de nuevo en el changeset de invoices le llegaba una lista vacía y la suma era 0

2022-03-03 18:14 UTC, peillis approved these changes

2022-03-03 18:14 UTC, merged