Rodri/duplicate
peillis/siwapp pull request #422
Opened 2022-03-02 13:36 UTC by RodrigoMolinaMadrid

Cada invoice seleccionada se duplica, esto es que se crea una nueva con todos los parámetros editables iguales (salvo el number que ha de ser único). Los payments no se duplican

2022-03-02 14:14 UTC, nurietzsche2021 commented on lib/siwapp_web/live/invoices_live/index.ex
> +      |> put_flash(:info, "Invoices succesfully deleted")
Pone invoices deleted en el flash. Además, deberías quitar el id=0 que corresponde al checkbox que hace que se marquen todas las facturas. Si no, peta

2022-03-02 14:16 UTC, nurietzsche2021 commented on lib/siwapp/invoices.ex
> +      :issue_date,
No merece más la pena hacer Map.from_struct? Poner esa lista de keys es una locura

2022-03-02 14:17 UTC, nurietzsche2021 requested changes
No queda bien poner params_keys ahí, cuando (en todo caso) ya tenemos @fields en el boundary de Invoice. Aún así, creo que no hace falta, si sobran campos, los ignora precisamente por el cast(@fields) del changeset, no?

2022-03-02 14:59 UTC, olirods commented on lib/siwapp/invoices.ex
> +      :issue_date,
O es mejor approach también hacer reject de los que no te interesan no?

2022-03-02 15:00 UTC, olirods commented on lib/siwapp/invoices.ex
> +      :issue_date,
O es mejor approach también hacer reject de los que no te interesan no?

2022-03-03 08:56 UTC, RodrigoMolinaMadrid commented on lib/siwapp/invoices.ex
> +      :issue_date,
Lo voy a hacer llamando a los fields de Invoices en una función

2022-03-03 09:53 UTC, nurietzsche2021 approved these changes

2022-03-03 10:08 UTC, olirods approved these changes

2022-03-03 10:54 UTC, peillis approved these changes

2022-03-03 10:54 UTC, merged