statistics tests
peillis/siwapp pull request #439
Opened 2022-03-03 13:18 UTC by olirods

- fixes #432 

He cambiado el nombre del fichero para que sea igual que los otros tests. Por esto aparece como todo ese contenido como nuevo pero lo único que he añadido es desde la línea 267 a la 339

2022-03-03 13:19 UTC, olirods commented on test/siwapp/invoices_test.exs
> +
Aquí empieza lo nuevo

2022-03-03 13:28 UTC, nurietzsche2021 approved these changes

2022-03-03 13:37 UTC, RodrigoMolinaMadrid approved these changes

2022-03-03 18:16 UTC, peillis requested changes
deberías hacer un módulo nuevo de test para las estadísticas. Normalmente a cada módulo se le hace un módulo correspondiente de tests.

2022-03-04 08:44 UTC, peillis approved these changes

2022-03-04 08:44 UTC, merged