Use only one gen server and remove user_tokens per week
peillis/siwapp pull request #498
Opened 2022-03-08 11:08 UTC by Pabloj20

2022-03-08 11:39 UTC, nurietzsche2021 approved these changes

2022-03-08 12:20 UTC, peillis requested changes

2022-03-08 12:20 UTC, peillis commented on lib/siwapp/accounts/user_token.ex
> +  def verify_user_token do
Este nombre de fn, no es que sea malo, es que no tiene nada que ver. @nurietzsche2021 esto deberías detectarlo tú también.

2022-03-09 09:56 UTC, peillis approved these changes

2022-03-09 09:56 UTC, merged