Pablo/heroku
peillis/siwapp pull request #509
Opened 2022-03-18 09:30 UTC by Pabloj20

configuracion para deploy en heroku

2022-03-18 15:23 UTC, peillis requested changes

2022-03-18 15:23 UTC, peillis commented on config/prod.exs
> +  url: [scheme: "https", host: "nsiwapp-demo.herokuapp.com", port: 443],
nsiwapp-demo.herokuapp.com?

2022-03-18 15:23 UTC, peillis commented on priv/repo/seeds.exs
> +  RecurringInvoices.RecurringInvoice,
¿qué aporta este cambio?

2022-03-21 08:31 UTC, nurietzsche2021 commented on priv/repo/seeds.exs
> +  RecurringInvoices.RecurringInvoice,
Sí, yo quitaría este cambio

2022-03-21 08:35 UTC, nurietzsche2021 approved these changes

2022-03-21 08:35 UTC, nurietzsche2021 commented on config/prod.exs
> +  url: [scheme: "https", host: "nsiwapp-demo.herokuapp.com", port: 443],
Yo no le veo el fallo, en la documentación de HexDocs para hacer deploy en Heroku indican poner eso

2022-03-21 08:52 UTC, Pabloj20 commented on priv/repo/seeds.exs
> +  RecurringInvoices.RecurringInvoice,
Al introducir las seeds en heroku, al hacerse el Repo.delete_all, se tenían que borrar primero las invoices y las recurring invoices porque si no me daba error.

2022-03-21 08:56 UTC, Pabloj20 commented on config/prod.exs
> +  url: [scheme: "https", host: "nsiwapp-demo.herokuapp.com", port: 443],
![Captura de pantalla de 2022-03-21 09-55-42](https://user-images.githubusercontent.com/66000403/159230014-fff12c14-3b9f-4669-ab8f-0f0bf2fef4ab.png)

2022-03-21 08:56 UTC, Pabloj20 commented on config/prod.exs
> +  url: [scheme: "https", host: "nsiwapp-demo.herokuapp.com", port: 443],
Esto es lo que me aparece en el hexdocs para hacer el deploying en heroku

2022-03-21 09:14 UTC, peillis requested changes

2022-03-21 09:14 UTC, peillis commented on config/prod.exs
> +  url: [scheme: "https", host: "nsiwapp-demo.herokuapp.com", port: 443],
¿y que va a tener que hacer cualquier otro que lo quiera instalar en heroku? ¿Tiene que usar nuestro dominio también?

2022-03-21 09:30 UTC, peillis approved these changes
Ok, @Pabloj20 ponlo a funcionar en heroku y ya con las ramas main sincronizadas, y con los datos de doofinder para que podamos examinar si son correctos.
Gracias

2022-03-21 09:30 UTC, merged