Commons revisados
peillis/siwapp pull request #513
Opened 2022-03-18 13:22 UTC by nurietzsche2021

- He  arreglado que las tasas usadas en RecurringInvoices no se puedan borrar fixes #512 
- He hecho el index de name, enabled de series fixes #486
- He hecho los tests de commons

2022-03-21 08:50 UTC, Pabloj20 approved these changes

2022-03-21 09:37 UTC, Pabloj20 requested changes

2022-03-21 09:37 UTC, Pabloj20 commented on test/siwapp/commons_test.exs
> +    _series = series_fixture(%{name: "Default series", code: "D-"})
```suggestion
    series_fixture(%{name: "Default series", code: "D-"})
```
Y así con todas

2022-03-21 09:37 UTC, Pabloj20 commented on test/siwapp/commons_test.exs
> +                 acc and if x != series, do: not x.default, else: x.default
este reduce es un poco complejo de entender. No hay otra manera de hacerlo'

2022-03-21 10:03 UTC, Pabloj20 approved these changes

2022-03-21 10:39 UTC, peillis requested changes

2022-03-21 10:39 UTC, peillis commented on lib/siwapp/recurring_invoices/recurring_invoice_query.ex
> +  def num_of_rec_inv_whose_items_have_tax(query, tax_name) do
No nos importa el número sino el hecho de si existe o no alguna factura ¿no?
Creo que planteándolo así seguramente se simplifiquen cosas.

2022-03-22 10:27 UTC, peillis requested changes

2022-03-22 10:27 UTC, peillis commented on lib/siwapp/recurring_invoices/recurring_invoice_query.ex
> +  def any_rec_inv_items_have_tax?(query, tax_name) do
hay una convención con los interrogantes en las fn que dice que devuelven un booleano. En este caso no es así y eso puede generar confusión. Y sospecho que le pasa lo mismo a la fn de arriba.

2022-03-24 09:56 UTC, peillis requested changes

2022-03-24 09:56 UTC, peillis commented on lib/siwapp/recurring_invoices.ex
> +    |> Repo.one()
Repo.one no devuelve nunca un booleano, por otro lado seguramente sea más apropiado usar el exists de ecto

2022-03-24 11:30 UTC, peillis approved these changes

2022-03-24 11:30 UTC, merged