new graphql tests for invoices and customers
peillis/siwapp pull request #517
Opened 2022-03-21 12:30 UTC by Pabloj20

2022-03-21 13:28 UTC, nurietzsche2021 approved these changes

2022-03-22 10:21 UTC, peillis requested changes

2022-03-22 10:21 UTC, peillis commented on test/siwapp_web/graphql/customers_test.exs
> +      |> post("/graphql/graphiql", %{query: query})
graphiql no es el endpoint adecuado, ese endpoint es sólo para poder visualizar en dev y hacer pruebas. El endpoint a probar es /graphql

2022-03-23 12:19 UTC, peillis approved these changes

2022-03-23 12:19 UTC, merged