Task para escribir los datos random de demo
peillis/siwapp pull request #520
Opened 2022-03-22 11:13 UTC by nurietzsche2021

fixes #500

2022-03-22 11:50 UTC, Pabloj20 approved these changes

2022-03-22 12:26 UTC, peillis requested changes

2022-03-22 12:26 UTC, peillis commented on lib/mix/tasks/siwapp.setup.ex
> +defmodule Mix.Tasks.Siwapp.Setup do
Esto tiene muy poco de setup, pensad los nombres por favor. ¿Qué es lo q va a pensar cualquiera si ve "setup"? ¿que le va a meter datos aleatorios?

2022-03-23 12:19 UTC, Pabloj20 approved these changes

2022-03-23 16:02 UTC, peillis requested changes
El script de demo tiene que reestablecer todo, user, templates, settings. ¿Qué pasaría p.ej si la gente modifica el template en la demo? ¿Ya nunca más se va a ver bien? Si crean usuarios nuevos, etc...
El deploy no tiene NADA que ver con esto. Esto es un script para que se ejecute SOLO en la web de demo, y su objetivo es sencillamente un reset de TODOS los datos.
Por otro lado, el seeds tiene que meter lo estrictamente necesario para que alguien pueda empezar a usar la aplicación, es decir, templates... y no sé si algo más hace falta, pero creo que no.
Tal y como lo hemos estado usando hasta ahora, metiendo invoices de ejemplo etc, no es su uso adecuado. Para meter invoices de ejemplo se puede usar otra task. A su vez esa task puede ser usada por la task del reset de demo, etc.

2022-03-24 11:08 UTC, Pabloj20 approved these changes

2022-03-24 11:08 UTC, Pabloj20 commented on lib/mix/tasks/siwapp.demo.ex
> +      admin: "true"
```suggestion
      admin: true
```

2022-03-31 08:12 UTC, nurietzsche2021 commented on lib/siwapp/invoices.ex
> +    e in ArgumentError -> {:error, e.message}
El argument error es que cuando hacemos Mix.Task.run("app.start") para usar la db, también se inicia TimerEvents y puede que no hubiera currency o days_to_due guardadas

2022-03-31 08:13 UTC, nurietzsche2021 commented on lib/siwapp/invoices.ex
> +    e in ArgumentError -> {:error, e.message}
He dejado que se propague el error porque total, esas facturas se pueden crear más tarde ya que en esta tarea se dejan todos los settings y templates listos

2022-03-31 10:04 UTC, closed without merging