Nurietzsche/db setup
peillis/siwapp pull request #531
Opened 2022-03-31 10:10 UTC by nurietzsche2021

fixes #520

He cogido el planteamiento de siwapp/ror que mantiene en seeds los templates y settings para que se disponga de ellos desde el inicio de la aplicación. Para llenar la base de datos entera se usa la tarea mix siwapp.demo

Para los datos de demo, lo suyo sería que programemos un heroku scheduler para que se siga ejecutando cada x tiempo.

UPDATE: Ya he creado el scheduler y he preparado que corra la tarea cada día a las 7AM hasta recibir más indicaciones

2022-03-31 11:09 UTC, Pabloj20 commented on lib/siwapp/invoices/item.ex
> +        {:error, _msg} -> Commons.list_taxes()
por qué no sacar el msg directamente mas que llamar otra vez a la función?

2022-03-31 12:26 UTC, nurietzsche2021 commented on lib/siwapp/invoices/item.ex
> +        {:error, _msg} -> Commons.list_taxes()
Lo que estoy haciendo ahí es ignorar el mensaje de error, que sé que se debe a que la Cachex no se ha iniciado, e invoco a la función del listado de tasas desde db directamente

2022-04-01 07:38 UTC, Pabloj20 approved these changes

2022-04-01 08:10 UTC, peillis requested changes
Los seeds meten muchos settings y no deberian estar.

2022-04-01 08:10 UTC, peillis commented on lib/siwapp/commons.ex
> +    e in ArgumentError -> {:error, e.message}
esto sigue siendo raro. ¿Por qué este rescue?

2022-04-01 08:11 UTC, peillis commented
<img width="1392" alt="Screenshot 2022-04-01 at 10 07 02" src="https://user-images.githubusercontent.com/461037/161222975-52c765ba-6560-4594-95a5-334845c58d59.png">

2022-04-04 11:21 UTC, peillis requested changes
resuelve lo del cachex bien, please.

2022-04-06 16:40 UTC, peillis approved these changes

2022-04-06 16:40 UTC, merged