Pablo/totals info
peillis/siwapp pull request #532
Opened 2022-03-31 10:53 UTC by Pabloj20

#515 
La estructura que sale de la query de las taxes es la siguiente:
`%{ Tax1 => [ {currency1, total_currency1}, {currency2, total_currency2}, ...],
       Tax2 => [ {currency1, total_currency1}, {currency2, total_currency2}, ...],
        ....
       Taxn => [ {currency1, total_currency1}, {currency2, total_currency2}, ...]
}
`
![totals](https://user-images.githubusercontent.com/66000403/161039276-7c88ab8f-6654-496d-ae31-8d33d42cd5a9.png)

2022-03-31 12:30 UTC, nurietzsche2021 approved these changes

2022-04-01 08:01 UTC, peillis requested changes
Esto ahora mismo se calcula siempre que se entra a la página de invoices. Lo que hay que conseguir es que se ejecute sólo cuando se clica para que aparezca. Idealmente la gráfica igual.

2022-04-01 12:21 UTC, peillis requested changes
ok, los datos en una tabla serían más legibles. Gracias

2022-04-04 08:09 UTC, Pabloj20 commented
![totals](https://user-images.githubusercontent.com/66000403/161501502-8f81d7cb-134d-46a9-87e6-49973ba38852.png)

2022-04-04 08:47 UTC, merged