Nurietzsche/mailers
peillis/siwapp pull request #536
Opened 2022-03-31 12:27 UTC by nurietzsche2021

fixes #485 

Nunca he escrito configuración dinámica, parece bastante metaprogramación, pero creo que lo que he hecho funciona

2022-04-01 07:36 UTC, Pabloj20 approved these changes

2022-04-01 12:09 UTC, peillis commented on config/runtime.exs
> +  mailer_module = String.to_atom("Siwapp.#{mailer}Mailer")
Este módulo no va a existir, el único que hay es Siwapp.Mailer

2022-04-04 11:14 UTC, peillis requested changes
por favor, comprueba que realmente funciona

2022-04-06 16:34 UTC, peillis approved these changes

2022-04-06 16:34 UTC, merged