Impedimento para dejar defaults vacíos
peillis/siwapp pull request #541
Opened 2022-04-05 16:58 UTC by nurietzsche2021

fixes #539

2022-04-06 07:05 UTC, Pabloj20 commented on lib/siwapp_web/live/templates_live/index.ex
> +        {:noreply, push_redirect(socket, to: Routes.templates_index_path(socket, :index))}
por qué ese push redirect en vez de listar las templates como en el main?

2022-04-06 07:08 UTC, Pabloj20 commented
de todas formas incorporaría una mejora que fuera que si se clica sobre un default(el que no está como true en lBBDD) que el otro se desactivara(que se pusiera a false).

2022-04-06 07:42 UTC, nurietzsche2021 commented on lib/siwapp_web/live/templates_live/index.ex
> +        {:noreply, push_redirect(socket, to: Routes.templates_index_path(socket, :index))}
El push redirect es la manera más fácil para borrar el flash de error

2022-04-06 07:43 UTC, nurietzsche2021 commented
> de todas formas incorporaría una mejora que fuera que si se clica sobre un default(el que no está como true en lBBDD) que el otro se desactivara(que se pusiera a false).

Eso ya pasa, Pablo

2022-04-06 08:51 UTC, Pabloj20 approved these changes

2022-04-06 16:51 UTC, peillis requested changes
Este chequeo no puede ser de la vista, sino mas profundo. No debería poder hacerlo tampoco por terminal.

2022-04-07 07:56 UTC, Pabloj20 approved these changes

2022-04-07 08:04 UTC, peillis approved these changes

2022-04-07 08:04 UTC, merged