Pablo/invoices live
peillis/siwapp pull request #80
Opened 2021-12-22 11:42 UTC by Pabloj20

Customer_name and reference data are not the correct ones. I have just rendered some random fields from the invoice schema to see if it works

2021-12-22 11:43 UTC, Pabloj20 commented
![Captura de pantalla de 2021-12-22 12-43-58](https://user-images.githubusercontent.com/66000403/147087831-52980df0-a773-46c8-8597-f6c9f030ade8.png)

2021-12-22 11:47 UTC, Pabloj20 commented
#24

2021-12-22 12:27 UTC, peillis requested changes
change data structures

2021-12-22 14:23 UTC, peillis requested changes

2021-12-22 14:23 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +end
Think about the state. There can be "no possible" situations with your actual variables. For example there could be checked invoices and the buttons be invisible.
Remember to design a state where there can't be "impossible" states.

2021-12-22 14:23 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +    update_checked = socket.assigns.checked ++ [id]
```suggestion
    update_checked = [id | socket.assigns.checked]
```

2021-12-22 14:23 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +     |> assign(:checked, [])}
MapSet would be better than a list. MapSet guarantees there is no item repeated

2021-12-22 14:23 UTC, peillis commented on lib/siwapp_web/live/live_helpers.ex
> +      |> Enum.find(fn n -> n == string_id end)
Enum.member? is better for this

2021-12-22 14:23 UTC, peillis commented on lib/siwapp_web/live/live_helpers.ex
> +  def pending?(due_date) do
pending is more complicated than this. If the invoice is paid it's not pending.

2021-12-23 09:26 UTC, peillis requested changes
fix

2021-12-23 10:20 UTC, peillis requested changes
think! damn it!

2021-12-23 12:10 UTC, peillis requested changes
rf the index.ex

2021-12-23 12:10 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +      |> MapSet.put("0")
You can write this as MapSet.new(["0"])

2021-12-23 12:37 UTC, peillis requested changes

2021-12-23 12:37 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +    add_zero =
bad name

2021-12-23 12:37 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +    |> Enum.reduce(add_zero, fn invoice, mapset ->
wrongly use of reduce

2021-12-23 18:41 UTC, peillis requested changes

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +    IO.inspect(checked)
I see you don't check your PRs before me. Please, ALWAYS do that, and don't tell me I forgot to delete that. 
What you forgot is to see the changes you want to merge.

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +  def handle_event("click_checkbox", data, socket) do
as a convention what you call here data is usually called params. Please rename that.

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +    |> MapSet.new(fn invoice -> invoice.id end)
```suggestion
    |> MapSet.new(& &1.id)
```

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +     )}
all this tuple in a single line would be more readable

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +end
Good, bit by bit is getting much more simple. You should compare this code with your initial proposal.

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/live_helpers.ex
> +
write specs for these fns below

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/live_helpers.ex
> +  def status(paid, due_date) do
This status fn should go to the Invoices context. It's not just a helper for liveview, it's something more internal of every invoice.

2021-12-23 18:41 UTC, peillis commented on lib/siwapp_web/live/live_helpers.ex
> +  def invisible?(checked) do
instead of writing a fn which does just 1 thing, use the fn below and use it directly in the template

2022-01-04 10:27 UTC, peillis requested changes
Además corrige los errores que salen del `mix credo --strict`
Gracias

2022-01-04 10:27 UTC, peillis commented on lib/siwapp/invoices.ex
> +  end
Esta fn no tiene mucho sentido. Lo ideal sería tener una tipo `status(invoice)`

2022-01-04 10:27 UTC, peillis commented on lib/siwapp_web/live/invoices_live/index.ex
> +     |> assign(:status, Invoices.status_per_id())}
No hace falta esta variable en el socket, ya tienes las invoices.

2022-01-04 11:15 UTC, peillis approved these changes

2022-01-04 11:15 UTC, peillis commented on lib/siwapp/invoices.ex
> +  def status(invoice) do
Escribe @specs please

2022-01-04 11:16 UTC, merged