Pablo/navbar menu
peillis/siwapp pull request #89
Opened 2021-12-23 12:12 UTC by Pabloj20

Customers it is not implemented

2021-12-23 12:13 UTC, Pabloj20 commented
#81

2021-12-23 12:42 UTC, peillis requested changes

2021-12-23 12:42 UTC, peillis commented on lib/siwapp_web/templates/layout/root.html.heex
> +          %>
this is really weird, please see how this is usually done. Check docs

2021-12-23 12:42 UTC, peillis commented on priv/repo/seeds.exs
> +alias Siwapp.Invoices
this file shouldn't be here, must be part of another PR

2022-01-04 10:40 UTC, peillis requested changes

2022-01-04 10:40 UTC, peillis commented on lib/siwapp_web/templates/layout/root.html.heex
> +            <%= live_redirect "Invoices", to: Routes.page_path(@conn, :invoices), class: "navbar-item" %>
¿por qué no usas aquí el invoice_index_path y usas el page_path?

2022-01-04 11:09 UTC, Pabloj20 commented on lib/siwapp_web/templates/layout/root.html.heex
> +            <%= live_redirect "Invoices", to: Routes.page_path(@conn, :invoices), class: "navbar-item" %>
porque en mi rama invoice_index_path no existe, es decir, al hacer mix phx.routes me sale que /invoices es una página estática y no de tipo LiveView y es por eso que tengo que usar page_path

2022-01-04 11:12 UTC, peillis approved these changes

2022-01-04 11:12 UTC, merged